# Generated by Django 3.2.6 on 2021-08-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='open',
            field=models.CharField(choices=[('all', '모두공개'), ('follow', '이웃공개'), ('private', '비공개')], default='all', max_length=10),
        ),
    ]
